src/components/commons/Button.tsx, src/screens/testScreen1.tsx, src/types/commonComponents.ts
=> ♻️ Refactor: Button 컴포넌트 width 설정가능하도록 수정

src/screens/testScreen2.tsx
- testScreen2에 코드입력 후 배포되는지 테스트
.
ci/cd 테스트
=> Test: cicd 동작 확인

package-lock.json, package.json, src/apis/health/health.d.ts, src/apis/health/health.keys.ts, src/apis/health/health.ts, src/apis/register/register.d.ts, src/apis/register/register.keys.ts, src/apis/register/register.ts, src/main.tsx, src/screens/testScreen1.tsx, src/types/APIResponse.d.ts, src/utils/LoginAndRegister/RegisterApi.ts, src/utils/QueryClinet.ts, src/utils/axios.ts, tsconfig.json, vite.config.ts
=> ✨ Feat: React Query 설정

index.html, src/components/commons/rootRouter.tsx, src/screens/LoginAndRegister/AppleLoginCallback.tsx, src/screens/LoginAndRegister/LoginScreen.tsx, src/screens/LoginAndRegister/RegisterScreen.tsx, src/types/LoginAndRegisterComponents.ts, src/utils/LoginAndRegister/AppleLogin.ts
#17
apple OAuth 적용 
apple login 시 authroization json 가져오는 것 확인
env에 VITE_APP_APPLE_CLIENT_ID 추가
근데 localhost에서 OAuth성공 시 redirectURI로 이동하지 않음 ( 오류 )
=> Feat: apple OAuth

src/screens/LoginAndRegister/AppleLoginCallback.tsx, src/utils/LoginAndRegister/AppleLogin.ts
- 리디렉션 시 데이터를 쿼리스트링에 포함하도록 설정
- 쿼리스트링에 포함된 데이터를 리디렉션된 컴포넌트에서 json으로 정제
=> Feat : apple Oauth 리디렉션 처리

package-lock.json, package.json, src/components/InsueBoarding/Step4.tsx, src/components/InsueBoarding/Step5.tsx, src/components/InsuePlanner/InsuePlannerAnswer.tsx, src/components/InsuePlanner/InsuePlannerComponents/AnswerBox.tsx, src/components/InsuePlanner/InsuePlannerComponents/HistoryItem.tsx, src/components/InsuePlanner/InsuePlannerComponents/QuestionBox.tsx, src/components/InsuePlanner/InsuePlannerLoading.tsx, src/components/InsuePlanner/InsuePlannerQuestion.tsx, src/components/commons/SearchBar.tsx, src/screens/InsuePlanner/InsuePlannerScreen.tsx, src/screens/testScreen2.tsx, src/types/InsuePlannerComponents.ts, src/types/commonComponents.ts
- 인슈플래너 화면 구현
- 애니메이션 적용
>  #28
인슈플래너 답변 화면 구현 ( 애니메이션 적용 )
react-typed 라이브러리 사용
=> ✨ Feat: 인슈플래너 답변 화면 구현

src/apis/insueboarding/insueboarding.ts, src/components/InsueBoarding/Complete.tsx, src/components/InsueBoarding/Step4.tsx, src/components/InsueBoarding/Step5.tsx, src/components/commons/InsureCard.tsx, src/main.tsx, src/utils/axios.ts, src/utils/common/convertInsureType.ts
- 인슈보딩 UI 수정
- API 연동 ( 추가 작업 필요 )
> #34
- 인슈보딩 수정
- API 연동
=> ✨ Feat: 인슈보딩 UI 수정 및 API 연동

src/components/commons/Header.tsx, src/screens/Main/MainScreen.tsx
=> ✨ Feat: 네비게이션바

src/screens/LoginAndRegister/AppleLoginCallback.tsx, src/utils/LoginAndRegister/AppleLogin.ts
fragment로 변경 후 서버로 POST전송
#44 
fragment 방식 변경 후 POST 연결 ( 추후 추가적인 api 작업 필요 )
=> 🐛 Fix: apple OAuth 방식변경

src/components/Main/InsueMainIcon.tsx, src/components/Question/CategoryItem.tsx, src/components/Question/QuestionAnswer.tsx, src/components/commons/Header.tsx, src/screens/Main/MainScreen.tsx, src/screens/Question/Question.tsx
=> ✨ Feat: 홈, QNA 화면 모바일 반응형 적용

src/components/InsueBoarding/Step2.tsx, src/components/InsueBoarding/Step3.tsx, src/components/InsueBoarding/Step4.tsx, src/components/InsueBoarding/Step5.tsx, src/components/commons/InsureCard.tsx, src/screens/LoginAndRegister/LoginScreen.tsx, src/screens/LoginAndRegister/RegisterAgree.tsx, src/screens/LoginAndRegister/RegisterScreen.tsx, src/static/insurebordCards.tsx
인슈보딩 모바일 반응형 구현
#46 
인슈보딩 모바일 반응형 구현
=> 💄 Design: 인슈보딩 모바일

src/components/Question/QuestionAnswer.tsx, src/screens/Main/MainScreen.tsx
> #47 
> 홈화면 캐릭터 이미지 위치 수정
> QNA 답변 상세보기 svg 수정
=> 💄 Design: 홈화면 캐릭터 이미지 위치, QNA 상세보기 svg 수정

src/components/InsueMap/InsueDetailIcon.tsx, src/components/InsueMap/InsueMapHeadSection.tsx, src/components/InsueMap/InsueMapSecondSection.tsx, src/components/commons/GradientBackground.tsx, src/screens/InsueMap/InsueMapScreen.tsx
> #53 
> 인슈 맵 모바일 대응
> GradientBackground Componenet 모바일 크기 설정
=> ✨ Feat: insueMap Mobile화면

src/screens/LoginAndRegister/GoogleLoginCallback.tsx, src/stores/useStore.ts
> 구글로그인
> 아직 진행중.
> 구글 로그인 화면에 강제로그인 버튼 생성.
=> 🐛 Fix: isLogin 값 체크하도록 수정

src/components/commons/Header.tsx
구글로그인 
> Head에서 로그인 상태 핸들링하여 페이지 이동
=> 🐛 Fix: Head에서 마이페이지 이동하도록 수정

package-lock.json, package.json, src/assets/icons/InsuePlanner/Menu.svg, src/components/InsuePlanner/InsuePlannerAnswer.tsx, src/components/InsuePlanner/InsuePlannerComponents/AnswerBox.tsx, src/components/InsuePlanner/InsuePlannerComponents/HistoryItem.tsx, src/components/InsuePlanner/InsuePlannerComponents/HistoryListContainer.tsx, src/components/InsuePlanner/InsuePlannerComponents/InsuePlannerAnswerMobileModal.tsx, src/components/InsuePlanner/InsuePlannerComponents/QuestionBox.tsx, src/reset.css, src/screens/InsuePlanner/InsuePlannerScreen.tsx, src/styles/media.ts, src/types/InsuePlannerComponents.ts
- 인슈플래너 답변 모바일화면 구현
- 모달 적용
#65 
인슈플래너 답변 화면 모바일 구현 
인슈플래너 완
=> ✨ Feat: 인슈플래너 답변 모바일

src/components/InsueBoarding/Step4.tsx, src/components/InsuePlanner/InsuePlannerQuestion.tsx, src/components/LoginAndRegister/OAuthButton.tsx, src/components/commons/InsureCard.tsx, src/components/commons/Selector.tsx
- webview ios 디자인 변경 ( 추가적인 작업 필요 )
#74
ios webview 대응 ( 추후 작업 필요 )
=> design : webview ios

src/screens/Main/MainScreen.tsx
=> 🐛 Fix: IOS main 화면 이미지 랜더링 오류 수정 확인

src/apis/insuePlanner/insuePlanner.ts, src/apis/insueboarding/insueboarding.ts, src/apis/register/register.d.ts, src/apis/register/register.keys.ts, src/apis/register/register.ts, src/components/InsuePlanner/InsuePlannerQuestion.tsx, src/components/commons/FailAlarm.tsx, src/screens/InsuePlanner/InsuePlannerScreen.tsx, src/screens/LoginAndRegister/AppleLoginCallback.tsx, src/screens/LoginAndRegister/GoogleLoginCallback.tsx, src/screens/LoginAndRegister/RegisterNickname.tsx, src/stores/useStore.ts, src/utils/axios.ts
- 애플로그인 연결 ( 토큰 설정 및 로그인/회원가입 )
- 인슈플래너, 닉네임설정, 인슈보딩 토큰 적용
- 구글 로그인 추가작업 필요, 나머지 api 토큰 연결 필요
- 로그아웃, 회원탈퇴는 이후 마이페이지 완성 후 진행 ( 인슈플래너 스크린에 임의로 구현 )
#78
=> feat : 애플로그인 연결

src/components/InsueBoarding/Step5.tsx, src/components/commons/BottomNav.tsx, src/screens/InsueBording/InsueBordingScreen.tsx
=> 💄 Design: 인슈보딩 bottomnav 없앰. top 맞춤

src/components/InsueMap/InsueMapHeadSection.tsx, src/components/commons/BottomNav.tsx, src/screens/InsueMap/InsueMapScreen.tsx, src/screens/LoginAndRegister/LoginScreen.tsx
=> 💄 Design : 디자인 디버깅 수정

src/components/InsueBoarding/Congraulate.tsx, src/components/InsueBoarding/Step4.tsx, src/components/InsueBoarding/Step5.tsx, src/components/InsuePlanner/InsuePlannerQuestion.tsx, src/components/User/InfoSection.tsx, src/components/commons/FailAlarm.tsx, src/screens/LoginAndRegister/GoogleLoginCallback.tsx
#89
- 인슈플래너 로딩 처리
- 인슈플래너 에러 알람 처리
- step4,5 카드 집합 모바일 여백 제거
- step5 카드 배치 조정
- 회원가입 축하 메시지 수정
=> feat : 배포전 디테일 수정

src/apis/account/account.d.ts, src/apis/account/account.ts, src/components/User/InfoSection.tsx, src/screens/Main/PolicyPrivacyScreen.tsx, src/screens/Main/PolicyServiceScreen.tsx, src/screens/User/UserInfoScreen.tsx
> 마이페이지 API 연동
> 모바일 정책 화면 연결
> 정책 화면 폰트 크기 조정
=> ✨ Feat: 마이페이지 API 연결

src/components/User/InsueBarItem.tsx
=> 🐛 Fix: 내보험 클릭 수정

src/stores/useStore.ts
=> feat : zustand Persist 적용

src/components/InsueMap/RecommendSection.tsx
=> 🐛 Fix: 인슈 맵 추천 막기

src/components/InsueMap/InsueMapSecondSection.tsx
=> 💄 Design: 인슈 맵 보험사 이동 버튼 숨김

src/components/InsueMap/RecommendSection.tsx, src/screens/Question/Question.tsx, src/utils/common/InsurCategory.ts
=> ✨ Feat: QNA에서 가입한보험보기 API

src/components/InsueMap/RecommendItem.tsx
=> 💄 Design: 보험사 img 사이즈 조정

src/App.tsx, src/components/InsueBoarding/Step4.tsx, src/components/commons/Selector.tsx, src/stores/useStore.ts
#99
- 앱 마운트 시 플랫폼 정보 들고오기
- step4 수정
- 셀렉터 UI 크기 조정
=> 🐛 Fix: ios UI 오류

src/utils/common/InsurCategory.ts, src/utils/common/convertInsureType.ts
=> 🐛 Fix: 애견보험 수정

src/components/InsueMap/RecommendItem.tsx, src/components/InsueMap/RecommendSection.tsx
> 
> 인슈맵 추천 테이블에 head가 안보이던 현상 수정
=> 🐛 Fix: 추천 테이블 head

src/components/InsueMap2/Map.tsx
=> 🐛 Fix: 인슈맵 api 호출 수정

src/components/commons/Header.tsx
=> 💄 Design: head color

src/screens/Question/Question.tsx
> 디버깅시트29
> QNA 카테고리 목록을 보유보험에서 관심보험으로 수정
=> 🐛 Fix: QNA페이지 보유보험 > 관심보험 수정

src/components/User/CountSection.tsx, src/components/User/InfoSection.tsx, src/components/User/InsueSection.tsx, src/components/commons/rootRouter.tsx, src/screens/User/RegistInsueScreen.tsx, src/screens/User/UserInfoScreen.tsx
> 디버깅시트 41
> apple아이디 예외처리
> 보험수 추가
=> ✨ Feat: 마이페이지 보험수 추가

src/components/InsuePlanner/InsuePlannerAnswer.tsx, src/components/InsuePlanner/InsuePlannerComponents/AnswerBox.tsx, src/components/InsuePlanner/InsuePlannerQuestion.tsx
=> 💄 Design: 인슈플래너 글자크기 조정

src/components/InsueMap2/Map.tsx, src/components/commons/InsureCard.tsx
- 인슈카드 step5 트랜지션 수정
- 인슈맵 애니메이션 조정
=> 💄 Design: 인슈카드,인슈맵 애니메이션 수정

src/screens/Question/Question.tsx
=> 💄 Design: qna 로딩 중앙정렬

src/screens/Main/MainScreen.tsx
=> 🐛 Fix: 메인 스와이퍼 회전

src/utils/LoginAndRegister/Login.ts
> 디버깅시트 45
> google login 새창열기
=> 🐛 Fix: googleLogin Popup 설정

src/components/InsuePlanner/InsuePlannerAnswer.tsx, src/components/InsuePlanner/InsuePlannerComponents/AnswerBox.tsx
=> 🐛 Fix: 인슈플래너 답변화면 링크이동

src/components/Question/CategoryItem.tsx, src/components/Question/QuestionAnswer.tsx, src/components/User/InsueSection.tsx, src/screens/Question/Question.tsx, src/screens/User/RegistInsueScreen.tsx, src/screens/User/UserInfoScreen.tsx, src/utils/LoginAndRegister/Login.ts
=> 💄 Design: 디자인 수정

src/components/InsueBoarding/InsueBoardingCompononets/MonthPicker.tsx, src/components/InsueBoarding/InsueBoardingCompononets/YearPicker.tsx, src/components/InsueBoarding/Step1.tsx, src/components/InsueMap2/Map.tsx, src/screens/InsueMap2/InsueMap2Screen.tsx, src/screens/Main/MainScreen.tsx
=> 💄 Design: 인슈맵,인슈보딩 디자인 수정

src/components/Question/QuestionAnswer.tsx, src/components/commons/Header.tsx, src/screens/Main/MainScreen.tsx
=> 💄 Design: QNA, Main, Header 디자인

src/components/InsueMap2/Map.tsx
- 내 보험 폰트사이즈 수정
- 보유중인 보험만 애니메이션 적용
=> 💄 Design: 내 보험 수정

src/screens/Main/MainScreen.tsx
=> 💄 Design: 이용약관 버튼 추가

src/screens/Main/MainScreen.tsx, src/utils/common/openNewTab.ts, src/vite-env.d.ts
=> ✨ Feat: 새탭열기 Test

src/components/InsueMap/InsueMapSecondSection.tsx, src/components/InsueMap/RecommendItem.tsx, src/components/InsuePlanner/InsuePlannerComponents/AnswerBox.tsx, src/components/Question/QuestionAnswer.tsx, src/screens/Main/MainScreen.tsx, src/screens/User/UserInfoScreen.tsx, src/utils/common/openNewTab.ts
> 디버깅시트45
> 새탭 열기 부분 모두 앱 확인하도록 수정
=> 🐛 Fix: 새탭 열기 설정

src/utils/LoginAndRegister/AppleLogin.ts, src/utils/LoginAndRegister/Login.ts
=> ✨ Feat: 로그인에 새탭 적용

src/apis/account/account.d.ts, src/apis/account/account.keys.ts, src/apis/account/account.ts, src/components/User/InsueBarItem.tsx, src/components/User/InsueSection.tsx
=> ✨ Feat: 가입한 보험 수정 API 연동

src/screens/LoginAndRegister/AppleErrorCallback.tsx, src/screens/LoginAndRegister/AppleLoginCallback.tsx, src/screens/LoginAndRegister/GoogleLoginCallback.tsx, src/utils/LoginAndRegister/AppleLogin.ts, src/utils/LoginAndRegister/Login.ts, src/utils/common/openNewTab.ts
=> 🐛 Fix: 로그인 새창띄우기 수정

src/screens/LoginAndRegister/AppleErrorCallback.tsx, src/screens/LoginAndRegister/AppleLoginCallback.tsx, src/screens/LoginAndRegister/GoogleLoginCallback.tsx
=> 🐛 Fix: 로그인 새창 후 닫기 및 새로고침

src/utils/common/openNewTab.ts
=> 🐛 Fix: 로그인 후 새로고침

src/screens/LoginAndRegister/GoogleLoginCallback.tsx
=> 🐛 Fix: 구글 로그인 에러 메세지

package-lock.json, package.json, src/screens/Question/Question.tsx
=> ✨ Feat : QnA 무한스크롤에 가상화 기능 추가

src/screens/Question/Question.tsx
#150 
무한스크롤 가장 하단에서 Footer를 넘어가는 현상 해결
=> 🐛 Fix: 무한스크롤 하단 버그 수정

src/components/InsuePlanner/InsuePlannerComponents/InsuePlannerLoadingWithSkeleton.tsx, src/components/InsuePlanner/InsuePlannerQuestion.tsx
#153 
인슈플래너 답변 화면 전 로딩에 skeletonUI 추가
=> ✨ Feat: 인슈플래너 로딩 skeletonUI 추가
